import { TranslationSet, Product } from "./types";

export const TRANSLATIONS: Record<"en" | "ar", TranslationSet> = {
  en: {
    navHome: "Home",
    navAbout: "About",
    navProducts: "Products",
    navContact: "Contact",
    ctaInquiry: "Contact Us",
    heroTitle: "INDUSTRIAL PRECISION",
    heroTagline: "Engineering Excellence at Scale",
    heroDesc:
      "Elite global supplier of high-performance engine components, filtration systems, and industrial compressors.",
    heroBtnProducts: "View Brochure",
    heroBtnInquiry: "Technical Inquiry",
    statsProducts: "Inventory Units",
    statsProjects: "Global Deliveries",
    statsClients: "Key Partners",
    launchTitle: "Pioneering Air Power",
    launchBadge: "SYSTEM MODULE",
    aboutTitle: "RELIABILITY ENGINEERED",
    aboutSubtitle: "A Legacy of Industrial Trust",
    aboutText:
      "Focused on high-performance engine components and heavy-duty filtration. Our supply chain ensures zero downtime for global fleet owners and industrial projects.",
    productCategories: "CORE CAPABILITIES",
    faqTitle: "TECHNICAL SPECIFICATIONS & FAQ",
    contactTitle: "ESTABLISH PARTNERSHIP",
    footerTagline:
      "SMT is a Saudi Arabia–based company providing genuine engine spare parts and reliable maintenance and repair services, delivering quality you can trust since 2014.",
    whatsappTooltip: "Chat with us on WhatsApp",
    testimonialTitle: "OPERATIONAL VERDICTS",
  },
  ar: {
    navHome: "الرئيسية",
    navAbout: "من نحن",
    navProducts: "المنتجات",
    navContact: "اتصل بنا",
    ctaInquiry: "استفسار مباشر",
    heroTitle: "دقة صناعية",
    heroTagline: "التميز الهندسي على نطاق واسع",
    heroDesc:
      "مورد عالمي لنخبة مكونات المحركات، وأنظمة الترشيح، والضواغط الصناعية.",
    heroBtnProducts: "عرض الإمكانيات",
    heroBtnInquiry: "استفسار فني",
    statsProducts: "وحدات المخزون",
    statsExperience: "سنوات الخبرة",
    statsProjects: "تسليمات عالمية",
    statsClients: "شركاء رئيسيون",
    launchTitle: "ريادة طاقة الهواء: قسم الضواغط",
    launchBadge: "قسم جديد",
    aboutTitle: "موثوقية هندسية",
    aboutSubtitle: "إرث من الثقة الصناعية",
    aboutText:
      "نركز على مكونات المحركات عالية الأداء والترشيح الشاق. تضمن سلسلة التوريد الخاصة بنا عدم وجود فترات توقف لأصحاب الأساطيل العالمية.",
    productCategories: "القدرات الأساسية",
    faqTitle: "المواصفات الفنية والأسئلة الشائعة",
    contactTitle: "تأسيس شراكة",
    footerTagline: "تحديد معايير توريد قطع الغيار الصناعية منذ عام 1998.",
    whatsappTooltip: "تواصل معنا عبر واتساب",
    testimonialTitle: "تقارير الأداء",
  },
};

export const PRODUCTS: Product[] = [
  {
    id: "1",
    title: "V12 Piston Assembly",
    category: "engine",
    desc: "High-thermal tolerance alloy with precision coating.",
    specs: "Heavy Duty Marine & Industrial",
    image: "https://images.unsplash.com/photo-1429772011165-0c2e054367b8?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "2",
    title: "Multi-Stage Screw Compressor",
    category: "compressor",
    desc: "Oil-free compression for pharmaceutical applications.",
    specs: "350 CFM | Variable Speed",
    image: "https://images.unsplash.com/photo-1606337321936-02d1b1a4d5ef?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D ",
  },
  {
    id: "3",
    title: "Nanofiber Fuel Filter",
    category: "filter",
    desc: "Advanced particulate capture for high-pressure common rail systems.",
    specs: "Efficiency 99.9%",
    image: "https://images.unsplash.com/photo-1730201127761-15888d9ddf98?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "4",
    title: "Gasket Performance Kit",
    category: "spare",
    desc: "Full sealing solution for heavy earthmovers.",
    specs: "Heat Resilient Fluoroelastomer",
    image: "https://images.unsplash.com/photo-1759419281480-bacc913c9606?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "5",
    title: "Turbocharger Cartridge",
    category: "engine",
    desc: "Balanced assembly for high-efficiency turbo performance.",
    specs: "Precision Machined | Journal Bearing",
    image: "https://images.unsplash.com/photo-1600377232142-164c095e686e?q=80&w=1073&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "6",
    title: "Industrial Air Dryer",
    category: "compressor",
    desc: "Desiccant-based moisture removal for compressed air systems.",
    specs: "480V | -40°C Dew Point",
    image: "https://images.unsplash.com/photo-1705129472480-2145aecb9aaa?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "7",
    title: "Hydraulic Return Filter",
    category: "filter",
    desc: "High-dirt holding capacity and low pressure drop.",
    specs: "Flow Rate 120 L/min | 10 Micron",
    image: "https://images.unsplash.com/photo-1614447428943-52ec0bdbc7aa?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "8",
    title: "Valve Overhaul Kit",
    category: "spare",
    desc: "Complete set for rapid on-site valve maintenance.",
    specs: "NBR & Viton Options",
    image: "https://images.unsplash.com/photo-1763836393379-68f9721966ee?q=80&w=848&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "9",
    title: "Marine Cylinder Liner",
    category: "engine",
    desc: "Wear-resistant cast iron cylinder for marine diesel engines.",
    specs: "Honed Bore | Chrome Plated",
    image: "https://images.unsplash.com/photo-1552656967-7a0991a13906?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "10",
    title: "Oil-Water Separator",
    category: "compressor",
    desc: "Removes oil mist and vapor from condensate streams.",
    specs: "Auto-Drain | Polypropylene Body",
    image: "https://plus.unsplash.com/premium_photo-1682145074686-96a169644544?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "11",
    title: "High-Efficiency Cabin Filter",
    category: "filter",
    desc: "Captures allergens and fine particulates for cabin filtration.",
    specs: "Minimum Efficiency 97% | Activated Carbon",
    image: "https://images.unsplash.com/photo-1556838656-af51dadc2c93?q=80&w=1074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "12",
    title: "Universal Seal Kit",
    category: "spare",
    desc: "Multi-application sealing solution for pumps and valves.",
    specs: "Assorted Sizes | Chemical Resistant",
    image: "https://images.unsplash.com/photo-1727413434026-0f8314c037d8?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    quote:
      "Zero downtime since switching to IP's V12 piston kits. Their logistics team is surgical in their execution and delivery speed.",
    author: "Jameson H. Vance",
    position: "Fleet Operations Manager",
    company: "Global Logistics Corp",
    location: "Houston, TX",
  },
  {
    id: "t2",
    quote:
      "The Compressor Division's commissioning was flawless. We achieved 99.9% uptime in high-ambient desert conditions that killed our previous units.",
    author: "Omar Al-Fayed",
    position: "Operations Director",
    company: "Desert Peak Energy",
    location: "Dubai, UAE",
  },
  {
    id: "t3",
    quote:
      "Finding a supplier that actually understands engineering drawings without back-and-forth fluff is rare. Remarkable precision.",
    author: "Karl Schneider",
    position: "Chief Engineer",
    company: "Schneider-Werke",
    location: "Berlin, DE",
  },
];
